---
- hosts: all
  become: yes
  tasks: 
  - name: un install tree
    apt:
      name: tree
      state: absent
  - name: uninstall apache2
    apt:
      name: apache2
      state: absent
  - name: un-install nmap
    apt:
      name: nmap
      state: absent
  - name: un-install wget
    apt:
      name: wget
      state: absent
